apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elearning-uploads-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elearning-logs-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
